/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdio.h>
#include<stdint.h>
void delay(void);
int main(void)
{
	volatile uint32_t *pClkCntrlReg = (uint32_t *)0x40023830;
	volatile uint32_t *pGPIODModeReg = (uint32_t *)0x40020C00;
	volatile uint32_t *pGPIODopReg = (uint32_t *)0x40020C14;

	//1.enable clock for GPIOD peripheral in AHB1ENR
	// to set the GPIODEN that is in 3 bit so we use bitwise OR so mask value would be 0x00000008
	/*uint32_t temp = *pClkCntrlReg; //read
	temp = temp | 0x08;	//modify
	*pClkCntrlReg = temp; // write
	 a single line command for the above would be*/

	*pClkCntrlReg = *pClkCntrlReg|0x08;

	//2. Configure the mode of the IO pin as output
	// clear the 24th and 25th bit position that is for pin 12
	*pGPIODModeReg = *pGPIODModeReg & 0xfcffffff;
	//make the 24th bit as one so the gpio is in output mode
	*pGPIODModeReg = *pGPIODModeReg | 0x01000000;

	//3. Set the 12th bit of output data register to make i/o pin 12 high.
	// we have to set the 12th bit so mask value will be 0x00001000
	*pGPIODopReg = *pGPIODopReg | 0x00001000;

	while(1){
		*pGPIODopReg = *pGPIODopReg ^ 0x00001000;
		delay();
	}



}

void delay(void)
{
    for(uint32_t i = 0; i < 500000; i++);
}

