/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include<stdio.h>
#include<stdint.h>
void delay(void);
int main(void)
{
	volatile uint32_t *pClkCntrlReg = (uint32_t *)0x40023830;
	 volatile uint32_t *pGPIOAModeReg  = (uint32_t*)0x40020000; // GPIOA MODER
	volatile uint32_t *pGPIODModeReg = (uint32_t *)0x40020C00;  // GPIOD MODER
	volatile uint32_t *pGPIOAIdReg    = (uint32_t*)0x40020010; // GPIOA IDR
	volatile uint32_t *pGPIODopReg = (uint32_t *)0x40020C14;   // GPIOD ODR

	//we will enable clock both gpioa and gpiod pin
	// gpioa is in 0th bit and gpiod is in 3rd bit
	*pClkCntrlReg = *pClkCntrlReg|(1<<0);
	*pClkCntrlReg = *pClkCntrlReg|(1<<3);

	//2a. Configure the mode of the IO pin as output
		// clear the 24th and 25th bit position that is for pin 12 in gpiod
		// and for pin 1 0 & 1 th bit in gpioa
	*pGPIODModeReg = *pGPIODModeReg &(~(1<<24));
	*pGPIODModeReg = *pGPIODModeReg &(~(1<<25));
	*pGPIOAModeReg = *pGPIOAModeReg &(~(1<<0));
	*pGPIOAModeReg = *pGPIOAModeReg &(~(1<<1));

	/*2b
	 * after setting the ,oder pins as 00
	 * we will enable the first pin of each bit so it
	 * become 01 so that its in gpio mode i.e 24 and 0th pin
	 */
	*pGPIODModeReg = *pGPIODModeReg |(1<<24);


	while(1){
		if(*pGPIOAIdReg &(1<<0)){
			*pGPIODopReg = *pGPIODopReg|(1<<12);

		}
		else{
			*pGPIODopReg = *pGPIODopReg&(~(1<<12));
		}
	}

}
